name: Build Thesis + Presentation

on: [push]

jobs:
  build-thesis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v4
      - uses: extractions/setup-just@v3

      - name: Compile Thesis
        run: just thesis

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: thesis
          path: thesis.pdf
          if-no-files-found: error

  build-presentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v4
        with:
          typst-version: 0.11.1
      - uses: extractions/setup-just@v3

      - name: Compile Presentation
        run: just presentation

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: presentation
          path: presentation.pdf
          if-no-files-found: error

